cloudfoundry-incubator/quarks-utils

pkg/cmd/docker_image.go
This was introduced in cf-operator
=> Add default value to docker image tag cmd line switch

pkg/config/config.go, pkg/config/suite_test.go, pkg/meltdown/suite_test.go, pkg/names/names.go, pkg/versionedsecretstore/versioned_secret_store.go, pkg/versionedsecretstore/versioned_secret_store_test.go, testing/e2ehelper/e2e_helper.go
[#169095334](https://www.pivotaltracker.com/story/show/169095334)
=> Rename quarks resources

pkg/names/apigroup.go, testing/e2ehelper/e2e_helper.go
[#169095318](https://www.pivotaltracker.com/story/show/169095318)
=> Rename API group name to "quarks.cloudfoundry.org"

pkg/names/names.go, pkg/names/names_test.go, testing/machine/machine.go
* rename CalculateIGSecretName to InstanceGroupSecretName
[#169418463](https://www.pivotaltracker.com/story/show/169418463)
=> QuarksLink entanglement naming

testing/command_helper.go
* wait for pod deletion
* get pod names from selector
* wait for data
[#169418463](https://www.pivotaltracker.com/story/show/169418463)
=> Add more end to end test helpers

testing/command_helper.go
[#170573718](https://www.pivotaltracker.com/story/show/170573718)
=> WaitForData also waits for pod to exist

pkg/config/config.go
Also increase requeue delay to 30s
[#170627191](https://www.pivotaltracker.com/story/show/170627191)
=> Increase meltdown duration from 5s to 60s

.travis.yml, README.md, bin/coverage, bin/test-unit
One part of [#169117636](https://www.pivotaltracker.com/story/show/169117636)
=> Add badges for godoc, go report, coveralls

testing/command_helper.go, testing/e2ehelper/e2e_helper.go
[#170670919](https://www.pivotaltracker.com/story/show/170670919)
=> E2E helper can use helm3 binary if available

pkg/crd/crd.go
[#168692418](https://www.pivotaltracker.com/n/projects/2192232/stories/168692418)
=> Add preserveunknownfields field to crd spec

pkg/names/names.go, pkg/names/names_test.go, pkg/versionedsecretstore/versioned_secret_store.go
[#171433464](https://www.pivotaltracker.com/story/show/171433464)
=> Add sanitize func for sub domain names, up to 253 chars

pkg/cmd/logger.go, pkg/logger/logger.go
[#170841351](https://www.pivotaltracker.com/story/show/170841351)
=> Add logger package to support trace logging

pkg/cmd/monitored_id.go, pkg/cmd/namespaces.go, pkg/config/config.go, testing/e2ehelper/e2e_helper.go, testing/machine/machine.go, testing/testhelper/config.go
Also adds teardown all helper
[#165900520](https://www.pivotaltracker.com/story/show/165900520)
=> Add testing helper to create labeled namespaces

pkg/cmd/meltdown.go, pkg/config/config.go, pkg/config/config_test.go
Add cmd helper and also tests for shared config (`pkg/config`)
[#170670255](https://www.pivotaltracker.com/story/show/170670255)
=> Make Meltdown period configurable

pkg/versionedsecretstore/versioned_secret_store.go, pkg/versionedsecretstore/versioned_secret_store_test.go
[#172404604](https://www.pivotaltracker.com/n/projects/2192232/stories/172404604)
Part of https://github.com/cloudfoundry-incubator/quarks-job/pull/79
=> Add annotations arg in create secret func

pkg/versionedsecretstore/versioned_secret_store.go, pkg/versionedsecretstore/versioned_secret_store_test.go
[#172404604](https://www.pivotaltracker.com/n/projects/2192232/stories/172404604)
=> Rearrange annotation logic in create func

bin/coverage, bin/test-cli-e2e, bin/test-helm-e2e, bin/test-integration, bin/test-unit
Common scripts that can be used from both quarks-operator and quarks-jobs
[#172645579](https://www.pivotaltracker.com/story/show/172645579)
=> Add common scripts

bin/coverage
[#173054910](https://www.pivotaltracker.com/n/projects/2192232/stories/173054910)
=> Fix coverage in concourse

bin/lint
[#173009013](https://www.pivotaltracker.com/story/show/173009013)
=> Make vet exit the lint script with failure

bin/test-integration
Github action actions/upload-artifact is much more readable
=> Remove confusing ginkgo debug output

testing/e2ehelper/e2e_helper.go, testing/machine/machine.go
[#172993878](https://www.pivotaltracker.com/story/show/172993878)
=> Add UpdateService for e2e tests

bin/tools-shared-get-v1.sh
[#173008965](https://www.pivotaltracker.com/story/show/173008965)
=> Add bin/tools-shared-get-v1.sh to download the shared bin dir

bin/build-helm, bin/build-image, bin/deploy, bin/gen-fakes, bin/publish-helm-repo, bin/publish-image, testing/command_helper.go, testing/e2ehelper/e2e_helper.go
* build-helm/build-image use $PROJECT now
* deploy and publish-* from quarks-job
* gen-fakes was  unused
=> Add more shared scripts

bin/build-image
[#173657213](https://www.pivotaltracker.com/story/show/173657213)
=> Ensure quarks-operator image is named 'cf-operator'

testing/integration/environment.go, testing/integration/namespace.go
Trying to fix the 'ginkgo node timeout' bug.
=> Add NukeNamespaces shared integration test helper

pkg/monitorednamespace/predicate.go, pkg/skip/skip.go, pkg/util/util.go
[#173218516](https://www.pivotaltracker.com/story/show/173218516)
=> Moved from quarks-operator to be shared with quarks-statefulset

bin/dump_env.sh, pkg/skip/skip.go
Used in tests to dump the namespace
=> Add dump_env.sh to shared scripts

testing/command_helper.go, testing/e2ehelper/e2e_helper.go
[#172761524](https://www.pivotaltracker.com/story/show/172761524)
=> Add helm/kubectl helpers

bin/tools-shared-get-v1.sh
Install gnu-tar with `brew install gnu-tar`.
=> On Mac use gnu-tar if installed

bin/build-image, testing/integration/namespace.go
Our approach of finding the dump env script location seems complicated.
=> Fix DumpENV script location

.golangci.yml
Sync golangci-lint
[#174319825](https://www.pivotaltracker.com/story/show/174319825)
=> Update golangci-lint config

pkg/names/dockersource_test.go
[#169539930](https://www.pivotaltracker.com/story/show/169539930)
=> Add test for using docker image sha reference

pkg/names/dockersource_test.go, pkg/podref/references.go
Extracted the shared code from other quarks repos
=> Add podref package

bin/test-helm-e2e
=> Remove build-helm from test-helm

bin/test-cli-e2e, bin/test-integration, bin/test-unit
* e2e tests don't have a log
* integration test logs have an ID appended
* unit tests can have a log
=> Correct info about test logs location

bin/build-image, bin/test-cli-e2e, testing/command_helper.go, testing/e2ehelper/e2e_helper.go, testing/testhelper/logger.go
[#174254515](https://www.pivotaltracker.com/story/show/174254515)
=> Rename quarks-operator docker image

bin/publish-helm-repo, pkg/webhook/config.go, testing/command_helper.go
[#170670931](https://www.pivotaltracker.com/story/show/170670931)
=> Configurable webhook prefixes

testing/integration/namespace.go, testing/machine/machine.go
[#175512395](https://www.pivotaltracker.com/n/projects/2192232)
=> Fix flaky integration test by waiting for service account

testing/command_helper.go
[#176925668](https://www.pivotaltracker.com/n/projects/2192232/stories/176925668)
=> Add serviceworks func to check accessibility of the service

testing/command_helper.go
Also avoid duplicate pod names
[#176906742](https://www.pivotaltracker.com/story/show/176906742)
=> Add curl helper for e2e tests

testing/testhelper/fake_client_call_queue.go
[#2192232](https://www.pivotaltracker.com/n/projects/2192232)
=> Update NewCallQueue func
